/**
 * Property-Based Tests for AutoGeneratedCycleBanner Deep-Link Navigation
 *
 * **Feature: financial-overview-redesign, Property 6: AutoGeneratedCycleBanner deep-link navigation**
 *
 * For any auto-generated cycle in AutoGeneratedCycleBanner, clicking SHALL invoke
 * onClick with the cycle's paymentMethodId, enabling the parent to call
 * openCreditCardDetail with initialTab='billing-cycles'.
 *
 * **Validates: Requirements 9.1**
 *
 * @invariant Deep-Link Navigation: For any auto-generated cycle data, clicking the banner passes the correct paymentMethodId to onClick for deep-link navigation to billing-cycles tab.
 */

import { render, fireEvent, cleanup } from '@testing-library/react';
import { describe, test, expect, vi, afterEach } from 'vitest';
import fc from 'fast-check';
import AutoGeneratedCycleBanner from './AutoGeneratedCycleBanner';
import { safeDate, safeAmount } from '../test-utils/arbitraries';

afterEach(() => cleanup());

// ── Arbitraries ──

const autoGeneratedCycleArbitrary = () =>
  fc.record({
    paymentMethodId: fc.integer({ min: 1, max: 10000 }),
    displayName: fc.constantFrom('Visa', 'Mastercard', 'Amex', 'Discover', 'Capital One'),
    cycleEndDate: safeDate(),
    calculatedBalance: safeAmount({ min: 0, max: 50000 })
  });

const nonEmptyCycleList = () =>
  fc.array(autoGeneratedCycleArbitrary(), { minLength: 1, maxLength: 5 })
    .filter(cycles => {
      // Ensure unique paymentMethodIds to avoid key collisions
      const ids = cycles.map(c => c.paymentMethodId);
      return new Set(ids).size === ids.length;
    });

// ── Property Tests ──

describe('AutoGeneratedCycleBanner - Deep-Link Navigation Properties', () => {
  /**
   * **Feature: financial-overview-redesign, Property 6: AutoGeneratedCycleBanner deep-link navigation**
   *
   * For a single auto-generated cycle, clicking the banner SHALL invoke onClick
   * with that cycle's paymentMethodId.
   *
   * **Validates: Requirements 9.1**
   */
  test('Property 6: Single cycle click passes paymentMethodId to onClick', () => {
    fc.assert(
      fc.property(
        autoGeneratedCycleArbitrary(),
        (cycle) => {
          const onClick = vi.fn();

          const { getByTestId, unmount } = render(
            <AutoGeneratedCycleBanner
              cycles={[cycle]}
              onDismiss={() => {}}
              onClick={onClick}
            />
          );

          const banner = getByTestId('auto-generated-cycle-banner');
          fireEvent.click(banner);

          // Property: onClick is called exactly once with the cycle's paymentMethodId
          expect(onClick).toHaveBeenCalledTimes(1);
          expect(onClick).toHaveBeenCalledWith(cycle.paymentMethodId);

          unmount();
        }
      ),
      { numRuns: 100 }
    );
  });

  /**
   * For multiple auto-generated cycles, clicking the banner SHALL invoke onClick
   * with the first cycle's paymentMethodId.
   *
   * **Validates: Requirements 9.1**
   */
  test('Property 6 (multiple): Multiple cycles banner click passes first paymentMethodId', () => {
    fc.assert(
      fc.property(
        nonEmptyCycleList().filter(c => c.length >= 2),
        (cycles) => {
          const onClick = vi.fn();

          const { getByTestId, unmount } = render(
            <AutoGeneratedCycleBanner
              cycles={cycles}
              onDismiss={() => {}}
              onClick={onClick}
            />
          );

          const banner = getByTestId('auto-generated-cycle-banner');
          fireEvent.click(banner);

          // Property: onClick is called with the first cycle's paymentMethodId
          expect(onClick).toHaveBeenCalledTimes(1);
          expect(onClick).toHaveBeenCalledWith(cycles[0].paymentMethodId);

          unmount();
        }
      ),
      { numRuns: 100 }
    );
  });

  /**
   * Keyboard navigation also passes correct paymentMethodId.
   */
  test('Property 6 (keyboard): Enter/Space key passes paymentMethodId to onClick', () => {
    fc.assert(
      fc.property(
        autoGeneratedCycleArbitrary(),
        fc.constantFrom('Enter', ' '),
        (cycle, key) => {
          const onClick = vi.fn();

          const { getByTestId, unmount } = render(
            <AutoGeneratedCycleBanner
              cycles={[cycle]}
              onDismiss={() => {}}
              onClick={onClick}
            />
          );

          const banner = getByTestId('auto-generated-cycle-banner');
          fireEvent.keyDown(banner, { key });

          expect(onClick).toHaveBeenCalledTimes(1);
          expect(onClick).toHaveBeenCalledWith(cycle.paymentMethodId);

          unmount();
        }
      ),
      { numRuns: 100 }
    );
  });
});
