import React from 'react';
import { formatCAD as formatCurrency } from '../utils/formatters';
import './AutoGeneratedCycleBanner.css';

/**
 * Banner component for auto-generated billing cycle notifications
 * Alerts users when the scheduler has created a billing cycle record
 * so they can review the calculated balance and enter the actual statement balance.
 * Uses teal/cyan color scheme to differentiate from other reminder types.
 * _Requirements: 2.1, 2.2, 2.3_
 */
const AutoGeneratedCycleBanner = ({ 
  cycles, 
  onDismiss, 
  onClick 
}) => {
  if (!cycles || cycles.length === 0) {
    return null;
  }

  /**
   * Format date for display
   */
  const formatDate = (dateString) => {
    if (!dateString) return '';
    const date = new Date(dateString + 'T00:00:00');
    return date.toLocaleDateString('en-CA', {
      month: 'short',
      day: 'numeric'
    });
  };

  const handleClick = (e, paymentMethodId) => {
    if (e.target.closest('.reminder-dismiss-btn')) {
      return;
    }
    if (onClick) {
      onClick(paymentMethodId);
    }
  };

  const handleDismiss = (e) => {
    e.stopPropagation();
    if (onDismiss) {
      onDismiss();
    }
  };

  const handleKeyDown = (e, paymentMethodId) => {
    if (e.key === 'Enter' || e.key === ' ') {
      e.preventDefault();
      handleClick(e, paymentMethodId);
    }
  };

  /**
   * Build message based on number of cycles
   * _Requirements: 2.1_
   */
  const buildMessage = () => {
    if (cycles.length === 1) {
      return `Auto-generated billing cycle created for ${cycles[0].displayName}`;
    }
    return `${cycles.length} auto-generated billing cycles created`;
  };

  // Single cycle view
  if (cycles.length === 1) {
    const cycle = cycles[0];

    return (
      <div 
        className="auto-generated-cycle-banner" 
        onClick={(e) => handleClick(e, cycle.paymentMethodId)} 
        onKeyDown={(e) => handleKeyDown(e, cycle.paymentMethodId)}
        role="button" 
        tabIndex={0}
        aria-label={`Auto-generated billing cycle for ${cycle.displayName}, ending ${formatDate(cycle.cycleEndDate)}, calculated balance ${formatCurrency(cycle.calculatedBalance)}. Click to review.`}
        data-testid="auto-generated-cycle-banner"
      >
        <div className="reminder-content">
          <span className="reminder-icon">🔄</span>
          <div className="reminder-details">
            <span className="reminder-message">{buildMessage()}</span>
            <div className="reminder-cycle-info">
              <span className="reminder-cycle-dates" data-testid="cycle-end-date">
                Cycle ended: {formatDate(cycle.cycleEndDate)}
              </span>
              <span className="reminder-calculated-balance" data-testid="calculated-balance">
                Calculated: {formatCurrency(cycle.calculatedBalance)}
              </span>
            </div>
            <span className="reminder-action-hint">Click to review and enter actual statement balance</span>
          </div>
        </div>
        <button 
          className="reminder-dismiss-btn" 
          onClick={handleDismiss}
          aria-label="Dismiss notification"
        >
          ×
        </button>
      </div>
    );
  }

  // Multiple cycles view
  return (
    <div 
      className="auto-generated-cycle-banner" 
      onClick={(e) => handleClick(e, cycles[0].paymentMethodId)} 
      onKeyDown={(e) => handleKeyDown(e, cycles[0].paymentMethodId)}
      role="button" 
      tabIndex={0}
      aria-label={`${cycles.length} auto-generated billing cycles created. Click to review.`}
      data-testid="auto-generated-cycle-banner"
    >
      <div className="reminder-content">
        <span className="reminder-icon">🔄</span>
        <div className="reminder-details">
          <span className="reminder-message">{buildMessage()}</span>
          <div className="reminder-cards-list">
            {cycles.map(cycle => (
              <div 
                key={cycle.paymentMethodId} 
                className="reminder-card-item"
                onClick={(e) => {
                  e.stopPropagation();
                  if (onClick) onClick(cycle.paymentMethodId);
                }}
                role="button"
                tabIndex={0}
                onKeyDown={(e) => {
                  if (e.key === 'Enter' || e.key === ' ') {
                    e.preventDefault();
                    e.stopPropagation();
                    if (onClick) onClick(cycle.paymentMethodId);
                  }
                }}
              >
                <span className="reminder-card-name">{cycle.displayName}</span>
                <span className="reminder-card-cycle">
                  Ended: {formatDate(cycle.cycleEndDate)}
                </span>
                <span className="reminder-card-balance">
                  {formatCurrency(cycle.calculatedBalance)}
                </span>
              </div>
            ))}
          </div>
          <span className="reminder-action-hint">Click a card to review its billing cycle</span>
        </div>
      </div>
      <button 
        className="reminder-dismiss-btn" 
        onClick={handleDismiss}
        aria-label="Dismiss notification"
      >
        ×
      </button>
    </div>
  );
};

export default AutoGeneratedCycleBanner;
