/**
 * Unit Tests for AutoGeneratedCycleBanner Component
 * Tests rendering, click navigation, dismiss behavior, and accessibility
 * _Requirements: 2.1, 2.2, 2.3_
 */

import { render, screen, fireEvent } from '@testing-library/react';
import { describe, test, expect, vi, beforeEach } from 'vitest';
import AutoGeneratedCycleBanner from './AutoGeneratedCycleBanner';

describe('AutoGeneratedCycleBanner', () => {
  const mockSingleCycle = {
    paymentMethodId: 4,
    displayName: 'Visa',
    cycleEndDate: '2026-02-15',
    calculatedBalance: 1234.56
  };

  const mockMultipleCycles = [
    {
      paymentMethodId: 4,
      displayName: 'Visa',
      cycleEndDate: '2026-02-15',
      calculatedBalance: 1234.56
    },
    {
      paymentMethodId: 7,
      displayName: 'Mastercard',
      cycleEndDate: '2026-02-19',
      calculatedBalance: 567.89
    }
  ];

  let mockCallbacks;

  beforeEach(() => {
    mockCallbacks = {
      onDismiss: vi.fn(),
      onClick: vi.fn()
    };
  });

  describe('Rendering - empty/null cycles', () => {
    test('should render nothing when cycles is empty array', () => {
      const { container } = render(
        <AutoGeneratedCycleBanner cycles={[]} {...mockCallbacks} />
      );
      expect(container.firstChild).toBeNull();
    });

    test('should render nothing when cycles is undefined', () => {
      const { container } = render(
        <AutoGeneratedCycleBanner cycles={undefined} {...mockCallbacks} />
      );
      expect(container.firstChild).toBeNull();
    });

    test('should render nothing when cycles is null', () => {
      const { container } = render(
        <AutoGeneratedCycleBanner cycles={null} {...mockCallbacks} />
      );
      expect(container.firstChild).toBeNull();
    });
  });

  describe('Single cycle display - Requirements: 2.1, 2.2', () => {
    test('should render banner with correct card name', () => {
      render(
        <AutoGeneratedCycleBanner cycles={[mockSingleCycle]} {...mockCallbacks} />
      );

      expect(screen.getByText(/Auto-generated billing cycle created for Visa/)).toBeInTheDocument();
    });

    test('should display cycle end date', () => {
      render(
        <AutoGeneratedCycleBanner cycles={[mockSingleCycle]} {...mockCallbacks} />
      );

      const endDate = screen.getByTestId('cycle-end-date');
      expect(endDate).toBeInTheDocument();
      expect(endDate).toHaveTextContent(/Feb.*15/);
    });

    test('should display calculated balance', () => {
      render(
        <AutoGeneratedCycleBanner cycles={[mockSingleCycle]} {...mockCallbacks} />
      );

      const balance = screen.getByTestId('calculated-balance');
      expect(balance).toBeInTheDocument();
      expect(balance).toHaveTextContent(/1,234\.56/);
    });

    test('should display action hint', () => {
      render(
        <AutoGeneratedCycleBanner cycles={[mockSingleCycle]} {...mockCallbacks} />
      );

      expect(screen.getByText(/Click to review and enter actual statement balance/)).toBeInTheDocument();
    });
  });

  describe('Multiple cycles display - Requirements: 2.1', () => {
    test('should display count of cycles', () => {
      render(
        <AutoGeneratedCycleBanner cycles={mockMultipleCycles} {...mockCallbacks} />
      );

      expect(screen.getByText(/2 auto-generated billing cycles created/)).toBeInTheDocument();
    });

    test('should display all card names', () => {
      render(
        <AutoGeneratedCycleBanner cycles={mockMultipleCycles} {...mockCallbacks} />
      );

      expect(screen.getByText('Visa')).toBeInTheDocument();
      expect(screen.getByText('Mastercard')).toBeInTheDocument();
    });

    test('should display cycle end dates for each card', () => {
      render(
        <AutoGeneratedCycleBanner cycles={mockMultipleCycles} {...mockCallbacks} />
      );

      expect(screen.getByText(/Feb.*15/)).toBeInTheDocument();
      expect(screen.getByText(/Feb.*19/)).toBeInTheDocument();
    });
  });

  describe('Click navigation - Requirements: 2.3', () => {
    test('should call onClick with paymentMethodId when single cycle banner is clicked', () => {
      render(
        <AutoGeneratedCycleBanner cycles={[mockSingleCycle]} {...mockCallbacks} />
      );

      const banner = screen.getByTestId('auto-generated-cycle-banner');
      fireEvent.click(banner);

      expect(mockCallbacks.onClick).toHaveBeenCalledWith(4);
    });

    test('should call onClick with correct paymentMethodId when individual card in multi-cycle view is clicked', () => {
      render(
        <AutoGeneratedCycleBanner cycles={mockMultipleCycles} {...mockCallbacks} />
      );

      const mastercardItem = screen.getByText('Mastercard').closest('.reminder-card-item');
      fireEvent.click(mastercardItem);

      expect(mockCallbacks.onClick).toHaveBeenCalledWith(7);
    });

    test('should handle keyboard Enter on single cycle banner', () => {
      render(
        <AutoGeneratedCycleBanner cycles={[mockSingleCycle]} {...mockCallbacks} />
      );

      const banner = screen.getByTestId('auto-generated-cycle-banner');
      fireEvent.keyDown(banner, { key: 'Enter' });

      expect(mockCallbacks.onClick).toHaveBeenCalledWith(4);
    });

    test('should handle keyboard Space on single cycle banner', () => {
      render(
        <AutoGeneratedCycleBanner cycles={[mockSingleCycle]} {...mockCallbacks} />
      );

      const banner = screen.getByTestId('auto-generated-cycle-banner');
      fireEvent.keyDown(banner, { key: ' ' });

      expect(mockCallbacks.onClick).toHaveBeenCalledWith(4);
    });
  });

  describe('Dismiss behavior', () => {
    test('should call onDismiss when dismiss button is clicked', () => {
      render(
        <AutoGeneratedCycleBanner cycles={[mockSingleCycle]} {...mockCallbacks} />
      );

      const dismissButton = screen.getByRole('button', { name: /dismiss notification/i });
      fireEvent.click(dismissButton);

      expect(mockCallbacks.onDismiss).toHaveBeenCalledTimes(1);
    });

    test('should NOT trigger onClick when dismiss button is clicked', () => {
      render(
        <AutoGeneratedCycleBanner cycles={[mockSingleCycle]} {...mockCallbacks} />
      );

      const dismissButton = screen.getByRole('button', { name: /dismiss notification/i });
      fireEvent.click(dismissButton);

      expect(mockCallbacks.onClick).not.toHaveBeenCalled();
    });

    test('should handle missing callbacks gracefully', () => {
      render(
        <AutoGeneratedCycleBanner cycles={[mockSingleCycle]} />
      );

      const banner = screen.getByTestId('auto-generated-cycle-banner');
      const dismissButton = screen.getByRole('button', { name: /dismiss notification/i });

      expect(() => {
        fireEvent.click(banner);
        fireEvent.click(dismissButton);
      }).not.toThrow();
    });
  });

  describe('Accessibility', () => {
    test('should have role="button" attribute', () => {
      render(
        <AutoGeneratedCycleBanner cycles={[mockSingleCycle]} {...mockCallbacks} />
      );

      const banner = screen.getByTestId('auto-generated-cycle-banner');
      expect(banner).toHaveAttribute('role', 'button');
    });

    test('should have tabIndex={0}', () => {
      render(
        <AutoGeneratedCycleBanner cycles={[mockSingleCycle]} {...mockCallbacks} />
      );

      const banner = screen.getByTestId('auto-generated-cycle-banner');
      expect(banner).toHaveAttribute('tabIndex', '0');
    });

    test('should have appropriate aria-label for single cycle', () => {
      render(
        <AutoGeneratedCycleBanner cycles={[mockSingleCycle]} {...mockCallbacks} />
      );

      const banner = screen.getByTestId('auto-generated-cycle-banner');
      const ariaLabel = banner.getAttribute('aria-label');
      expect(ariaLabel).toContain('Auto-generated billing cycle for Visa');
      expect(ariaLabel).toContain('Click to review');
    });

    test('should have appropriate aria-label for multiple cycles', () => {
      render(
        <AutoGeneratedCycleBanner cycles={mockMultipleCycles} {...mockCallbacks} />
      );

      const banner = screen.getByTestId('auto-generated-cycle-banner');
      const ariaLabel = banner.getAttribute('aria-label');
      expect(ariaLabel).toContain('2 auto-generated billing cycles created');
      expect(ariaLabel).toContain('Click to review');
    });

    test('should have accessible dismiss button with aria-label', () => {
      render(
        <AutoGeneratedCycleBanner cycles={[mockSingleCycle]} {...mockCallbacks} />
      );

      const dismissButton = screen.getByRole('button', { name: /dismiss notification/i });
      expect(dismissButton).toHaveAttribute('aria-label', 'Dismiss notification');
    });
  });
});
