/**
 * Property-Based Tests for Notification Banner Auto-Dismiss on Navigation
 *
 * **Feature: financial-overview-redesign, Property 11: Notification banner auto-dismiss on navigation**
 *
 * For any credit card notification banner (BillingCycleReminderBanner,
 * CreditCardReminderBanner, AutoGeneratedCycleBanner), when the banner's click
 * handler opens the CreditCardDetailView, the banner's onDismiss callback SHALL
 * be invoked.
 *
 * **Validates: Requirements 9.4**
 *
 * @invariant Auto-Dismiss: For any banner data, clicking the banner triggers both navigation (onClick) and dismissal (onDismiss) in the parent handler pattern.
 */

import { render, fireEvent, cleanup } from '@testing-library/react';
import { describe, test, expect, vi, afterEach } from 'vitest';
import fc from 'fast-check';
import BillingCycleReminderBanner from './BillingCycleReminderBanner';
import CreditCardReminderBanner from './CreditCardReminderBanner';
import AutoGeneratedCycleBanner from './AutoGeneratedCycleBanner';
import { safeDate, safeAmount } from '../test-utils/arbitraries';

afterEach(() => cleanup());

// ── Arbitraries ──

const billingCycleCardArbitrary = () =>
  fc.record({
    paymentMethodId: fc.integer({ min: 1, max: 10000 }),
    displayName: fc.constantFrom('Visa', 'Mastercard', 'Amex'),
    cycleStartDate: safeDate(),
    cycleEndDate: safeDate(),
    calculatedBalance: safeAmount({ min: 0, max: 50000 }),
    needsEntry: fc.constant(true),
    hasEntry: fc.constant(false)
  });

const creditCardArbitrary = () =>
  fc.record({
    id: fc.integer({ min: 1, max: 10000 }),
    paymentMethodId: fc.integer({ min: 1, max: 10000 }),
    display_name: fc.constantFrom('Visa', 'Mastercard', 'Amex'),
    full_name: fc.constant('Credit Card'),
    current_balance: fc.double({ min: 0, max: 10000, noNaN: true }).map(v => Math.round(v * 100) / 100),
    statement_balance: fc.double({ min: 0, max: 10000, noNaN: true }).map(v => Math.round(v * 100) / 100),
    required_payment: fc.double({ min: 0, max: 10000, noNaN: true }).map(v => Math.round(v * 100) / 100),
    credit_limit: fc.integer({ min: 1000, max: 50000 }),
    payment_due_day: fc.option(fc.integer({ min: 1, max: 28 }), { nil: null }),
    billing_cycle_day: fc.integer({ min: 1, max: 28 }),
    days_until_due: fc.integer({ min: -30, max: 30 }),
    is_statement_paid: fc.boolean(),
    is_overdue: fc.boolean(),
    is_due_soon: fc.boolean(),
    has_statement_pdf: fc.boolean(),
    cycle_start_date: fc.constant('2026-01-26'),
    cycle_end_date: fc.constant('2026-02-25')
  });

const autoGeneratedCycleArbitrary = () =>
  fc.record({
    paymentMethodId: fc.integer({ min: 1, max: 10000 }),
    displayName: fc.constantFrom('Visa', 'Mastercard', 'Amex'),
    cycleEndDate: safeDate(),
    calculatedBalance: safeAmount({ min: 0, max: 50000 })
  });

// ── Property Tests ──

describe('Notification Banner Auto-Dismiss Properties', () => {
  /**
   * **Feature: financial-overview-redesign, Property 11: Notification banner auto-dismiss on navigation**
   *
   * For BillingCycleReminderBanner: clicking triggers onClick (navigation),
   * and the parent handler pattern dismisses the banner after navigating.
   *
   * **Validates: Requirements 9.4**
   */
  test('Property 11a: BillingCycleReminderBanner click triggers both navigation and dismiss', () => {
    fc.assert(
      fc.property(
        fc.array(billingCycleCardArbitrary(), { minLength: 1, maxLength: 3 }),
        (cards) => {
          const onDismiss = vi.fn();
          let navigated = false;

          // Simulate SummaryPanel pattern: onClick navigates then dismisses
          const onClick = vi.fn((card) => {
            navigated = true;
            // Parent handler calls dismiss after navigation
            onDismiss();
          });

          const { getByTestId, unmount } = render(
            <BillingCycleReminderBanner
              cards={cards}
              onDismiss={onDismiss}
              onClick={onClick}
            />
          );

          const banner = getByTestId('billing-cycle-reminder-banner');
          fireEvent.click(banner);

          // Property: onClick was called (navigation happened)
          expect(onClick).toHaveBeenCalledTimes(1);
          expect(navigated).toBe(true);

          // Property: onDismiss was called (auto-dismiss after navigation)
          expect(onDismiss).toHaveBeenCalledTimes(1);

          unmount();
        }
      ),
      { numRuns: 100 }
    );
  });

  /**
   * For CreditCardReminderBanner: clicking triggers onClick (navigation),
   * and the parent handler pattern dismisses the banner after navigating.
   *
   * **Validates: Requirements 9.4**
   */
  test('Property 11b: CreditCardReminderBanner click triggers both navigation and dismiss', () => {
    fc.assert(
      fc.property(
        fc.array(creditCardArbitrary(), { minLength: 1, maxLength: 3 }),
        fc.boolean(),
        (cards, isOverdue) => {
          const onDismiss = vi.fn();
          let navigated = false;

          const onClick = vi.fn((card) => {
            navigated = true;
            onDismiss();
          });

          const { getByTestId, unmount } = render(
            <CreditCardReminderBanner
              cards={cards}
              isOverdue={isOverdue}
              onDismiss={onDismiss}
              onClick={onClick}
            />
          );

          const banner = getByTestId('credit-card-reminder-banner');
          fireEvent.click(banner);

          expect(onClick).toHaveBeenCalledTimes(1);
          expect(navigated).toBe(true);
          expect(onDismiss).toHaveBeenCalledTimes(1);

          unmount();
        }
      ),
      { numRuns: 100 }
    );
  });

  /**
   * For AutoGeneratedCycleBanner: clicking triggers onClick (navigation),
   * and the parent handler pattern dismisses the banner after navigating.
   *
   * **Validates: Requirements 9.4**
   */
  test('Property 11c: AutoGeneratedCycleBanner click triggers both navigation and dismiss', () => {
    fc.assert(
      fc.property(
        autoGeneratedCycleArbitrary(),
        (cycle) => {
          const onDismiss = vi.fn();
          let navigated = false;

          const onClick = vi.fn((paymentMethodId) => {
            navigated = true;
            onDismiss();
          });

          const { getByTestId, unmount } = render(
            <AutoGeneratedCycleBanner
              cycles={[cycle]}
              onDismiss={onDismiss}
              onClick={onClick}
            />
          );

          const banner = getByTestId('auto-generated-cycle-banner');
          fireEvent.click(banner);

          expect(onClick).toHaveBeenCalledTimes(1);
          expect(onClick).toHaveBeenCalledWith(cycle.paymentMethodId);
          expect(navigated).toBe(true);
          expect(onDismiss).toHaveBeenCalledTimes(1);

          unmount();
        }
      ),
      { numRuns: 100 }
    );
  });
});
