import { useState, useEffect, useCallback } from 'react';
import { API_ENDPOINTS } from '../config';
import IncomeManagementModal from './IncomeManagementModal';
import FixedExpensesModal from './FixedExpensesModal';
import LoansModal from './LoansModal';
import InvestmentsModal from './InvestmentsModal';
import TrendIndicator from './TrendIndicator';
import DataReminderBanner from './DataReminderBanner';
import CreditCardReminderBanner from './CreditCardReminderBanner';
import BillingCycleReminderBanner from './BillingCycleReminderBanner';
import AutoGeneratedCycleBanner from './AutoGeneratedCycleBanner';
import LoanPaymentReminderBanner from './LoanPaymentReminderBanner';
import InsuranceClaimReminderBanner from './InsuranceClaimReminderBanner';
import BudgetAlertManager from './BudgetAlertManager';
import NotificationsSection from './NotificationsSection';
import AutoLogPrompt from './AutoLogPrompt';
import PaymentMethodsModal from './PaymentMethodsModal';
import './SummaryPanel.css';

const SummaryPanel = ({ selectedYear, selectedMonth, refreshTrigger }) => {
  const [summary, setSummary] = useState(null);
  const [previousSummary, setPreviousSummary] = useState(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);
  const [showIncomeModal, setShowIncomeModal] = useState(false);
  const [showFixedExpensesModal, setShowFixedExpensesModal] = useState(false);
  const [showLoansModal, setShowLoansModal] = useState(false);
  const [showInvestmentsModal, setShowInvestmentsModal] = useState(false);
  const [loans, setLoans] = useState([]);
  const [totalOutstandingDebt, setTotalOutstandingDebt] = useState(0);
  const [investments, setInvestments] = useState([]);
  const [totalInvestmentValue, setTotalInvestmentValue] = useState(0);
  
  /**
   * Check if the selected month is in the future
   * Reminders and auto-log prompts should only show for current or past months
   */
  const isCurrentOrPastMonth = useCallback(() => {
    const now = new Date();
    const currentYear = now.getFullYear();
    const currentMonth = now.getMonth() + 1; // JavaScript months are 0-indexed
    
    if (selectedYear < currentYear) return true;
    if (selectedYear > currentYear) return false;
    return selectedMonth <= currentMonth;
  }, [selectedYear, selectedMonth]);
  
  // Reminder states
  const [reminderStatus, setReminderStatus] = useState({
    missingInvestments: 0,
    missingLoans: 0,
    hasActiveInvestments: false,
    hasActiveLoans: false,
    investments: [],
    loans: [],
    creditCardReminders: {
      overdueCount: 0,
      dueSoonCount: 0,
      hasActiveCreditCards: false,
      overdueCards: [],
      dueSoonCards: []
    },
    billingCycleReminders: {
      needsEntryCount: 0,
      hasCardsWithBillingCycle: false,
      cardsNeedingEntry: []
    },
    loanPaymentReminders: {
      overdueCount: 0,
      dueSoonCount: 0,
      hasLinkedExpenses: false,
      overduePayments: [],
      dueSoonPayments: []
    },
    insuranceClaimReminders: {
      pendingCount: 0,
      hasPendingClaims: false,
      pendingClaims: []
    },
    autoGeneratedCycleNotifications: {
      count: 0,
      cycles: []
    }
  });
  const [dismissedReminders, setDismissedReminders] = useState({
    investments: false,
    loans: false,
    creditCardOverdue: false,
    creditCardDueSoon: false,
    billingCycleEntry: false,
    loanPaymentOverdue: false,
    loanPaymentDueSoon: false,
    insuranceClaims: false,
    autoGeneratedCycles: false
  });
  
  // Budget alerts are now managed by BudgetAlertManager component
  // _Requirements: 6.1, 6.2, 6.4_
  const [budgetAlertsVisible, setBudgetAlertsVisible] = useState(false);
  
  // Payment Methods Modal state
  const [showPaymentMethodsModal, setShowPaymentMethodsModal] = useState(false);
  
  // Auto-log prompt state
  // _Requirements: 4.1, 4.4, 4.5_
  const [autoLogSuggestions, setAutoLogSuggestions] = useState([]);
  const [autoLogLoading, setAutoLogLoading] = useState(false);
  const [dismissedAutoLog, setDismissedAutoLog] = useState(false);
  
  // Collapsible panel states
  const [weeklyOpen, setWeeklyOpen] = useState(false);
  const [paymentOpen, setPaymentOpen] = useState(false);
  const [expenseTypesOpen, setExpenseTypesOpen] = useState(false);

  /**
   * Process summary data and update state
   * Handles both old (single summary) and new (current/previous) response formats
   */
  const processSummaryData = useCallback((data) => {
    if (data.current) {
      // New structure with previous month data
      setSummary(data.current);
      setPreviousSummary(data.previous);
      
      // Extract loan data from current summary
      if (data.current.loans && Array.isArray(data.current.loans)) {
        setLoans(data.current.loans);
        setTotalOutstandingDebt(data.current.totalOutstandingDebt || 0);
      } else {
        setLoans([]);
        setTotalOutstandingDebt(0);
      }
      
      // Extract investment data from current summary
      if (data.current.investments && Array.isArray(data.current.investments)) {
        setInvestments(data.current.investments);
        setTotalInvestmentValue(data.current.totalInvestmentValue || 0);
      } else {
        setInvestments([]);
        setTotalInvestmentValue(0);
      }
    } else {
      // Old structure (single summary)
      setSummary(data);
      setPreviousSummary(null);
      
      // Extract loan data from summary response
      if (data.loans && Array.isArray(data.loans)) {
        setLoans(data.loans);
        setTotalOutstandingDebt(data.totalOutstandingDebt || 0);
      } else {
        setLoans([]);
        setTotalOutstandingDebt(0);
      }
      
      // Extract investment data from summary response
      if (data.investments && Array.isArray(data.investments)) {
        setInvestments(data.investments);
        setTotalInvestmentValue(data.totalInvestmentValue || 0);
      } else {
        setInvestments([]);
        setTotalInvestmentValue(0);
      }
    }
  }, []);

  /**
   * Fetch reminder status from API
   */
  /**
   * Fetch reminder status from API
   * Only fetch for current or past months - future months don't need reminders
   */
  const fetchReminderStatus = useCallback(async () => {
    // Skip fetching reminders for future months
    if (!isCurrentOrPastMonth()) {
      setReminderStatus({
        missingInvestments: 0,
        missingLoans: 0,
        hasActiveInvestments: false,
        hasActiveLoans: false,
        investments: [],
        loans: [],
        creditCardReminders: {
          overdueCount: 0,
          dueSoonCount: 0,
          hasActiveCreditCards: false,
          overdueCards: [],
          dueSoonCards: []
        },
        billingCycleReminders: {
          needsEntryCount: 0,
          hasCardsWithBillingCycle: false,
          cardsNeedingEntry: []
        },
        loanPaymentReminders: {
          overdueCount: 0,
          dueSoonCount: 0,
          hasLinkedExpenses: false,
          overduePayments: [],
          dueSoonPayments: []
        },
        insuranceClaimReminders: {
          pendingCount: 0,
          hasPendingClaims: false,
          pendingClaims: []
        },
        autoGeneratedCycleNotifications: {
          count: 0,
          cycles: []
        }
      });
      return;
    }
    
    try {
      const response = await fetch(API_ENDPOINTS.REMINDER_STATUS(selectedYear, selectedMonth));
      
      if (!response.ok) {
        // Fail silently - don't block summary panel loading
        console.error('Failed to fetch reminder status');
        return;
      }

      const data = await response.json();
      setReminderStatus({
        missingInvestments: data.missingInvestments || 0,
        missingLoans: data.missingLoans || 0,
        hasActiveInvestments: data.hasActiveInvestments || false,
        hasActiveLoans: data.hasActiveLoans || false,
        investments: data.investments || [],
        loans: data.loans || [],
        creditCardReminders: data.creditCardReminders || {
          overdueCount: 0,
          dueSoonCount: 0,
          hasActiveCreditCards: false,
          overdueCards: [],
          dueSoonCards: []
        },
        billingCycleReminders: data.billingCycleReminders || {
          needsEntryCount: 0,
          hasCardsWithBillingCycle: false,
          cardsNeedingEntry: []
        },
        loanPaymentReminders: data.loanPaymentReminders || {
          overdueCount: 0,
          dueSoonCount: 0,
          hasLinkedExpenses: false,
          overduePayments: [],
          dueSoonPayments: []
        },
        insuranceClaimReminders: data.insuranceClaimReminders || {
          pendingCount: 0,
          hasPendingClaims: false,
          pendingClaims: []
        },
        autoGeneratedCycleNotifications: data.autoGeneratedCycleNotifications || {
          count: 0,
          cycles: []
        }
      });
    } catch (err) {
      // Fail silently - don't block summary panel loading
      console.error('Error fetching reminder status:', err);
    }
  }, [selectedYear, selectedMonth, isCurrentOrPastMonth]);

  /**
   * Fetch auto-log suggestions from API
   * Only fetch for current or past months - future months don't need auto-log prompts
   * _Requirements: 4.1, 4.4, 4.5_
   */
  const fetchAutoLogSuggestions = useCallback(async () => {
    // Skip fetching auto-log suggestions for future months
    if (!isCurrentOrPastMonth()) {
      setAutoLogSuggestions([]);
      return;
    }
    
    try {
      const response = await fetch(API_ENDPOINTS.AUTO_LOG_SUGGESTIONS(selectedYear, selectedMonth));
      
      if (!response.ok) {
        // Fail silently - don't block summary panel loading
        console.error('Failed to fetch auto-log suggestions');
        return;
      }

      const data = await response.json();
      setAutoLogSuggestions(data || []);
    } catch (err) {
      // Fail silently - don't block summary panel loading
      console.error('Error fetching auto-log suggestions:', err);
    }
  }, [selectedYear, selectedMonth, isCurrentOrPastMonth]);

  /**
   * Fetch summary data from API
   * Reusable function to avoid code duplication
   */
  const fetchSummaryData = useCallback(async () => {
    setLoading(true);
    setError(null);

    try {
      const response = await fetch(
        `${API_ENDPOINTS.SUMMARY}?year=${selectedYear}&month=${selectedMonth}&includePrevious=true`
      );

      if (!response.ok) {
        throw new Error('Failed to fetch summary data');
      }

      const data = await response.json();
      processSummaryData(data);
    } catch (err) {
      setError(err.message);
      console.error('Error fetching summary:', err);
    } finally {
      setLoading(false);
    }
  }, [selectedYear, selectedMonth, processSummaryData]);

  // Fetch summary when dependencies change
  // Budget alerts are now managed by BudgetAlertManager component
  useEffect(() => {
    fetchSummaryData();
    fetchReminderStatus();
    fetchAutoLogSuggestions();
  }, [fetchSummaryData, fetchReminderStatus, fetchAutoLogSuggestions, refreshTrigger]);

  // Reset dismissed reminders only when month/year changes (not on every refresh)
  // Budget alerts dismissal is managed by BudgetAlertManager
  useEffect(() => {
    setDismissedReminders({ 
      investments: false, 
      loans: false, 
      creditCardOverdue: false, 
      creditCardDueSoon: false, 
      billingCycleEntry: false, 
      loanPaymentOverdue: false, 
      loanPaymentDueSoon: false,
      insuranceClaims: false,
      autoGeneratedCycles: false
    });
    setDismissedAutoLog(false);
    // Don't reset budgetAlertsVisible here - let BudgetAlertManager control it via callback
  }, [selectedYear, selectedMonth]);

  // Modal handlers - simplified using shared fetch function
  const handleOpenIncomeModal = () => setShowIncomeModal(true);
  const handleOpenFixedExpensesModal = () => setShowFixedExpensesModal(true);
  const handleOpenLoansModal = () => setShowLoansModal(true);
  const handleOpenInvestmentsModal = () => setShowInvestmentsModal(true);

  const handleCloseIncomeModal = async () => {
    setShowIncomeModal(false);
    await fetchSummaryData();
  };

  const handleCloseFixedExpensesModal = async () => {
    setShowFixedExpensesModal(false);
    await fetchSummaryData();
  };

  const handleCloseLoansModal = async () => {
    setShowLoansModal(false);
    await fetchSummaryData();
    await fetchReminderStatus();
  };

  const handleCloseInvestmentsModal = async () => {
    setShowInvestmentsModal(false);
    await fetchSummaryData();
    await fetchReminderStatus();
  };

  const handleInvestmentsUpdate = async () => {
    // Refresh summary data without closing the modal
    await fetchSummaryData();
    // Also refresh reminder status
    await fetchReminderStatus();
  };

  // Reminder handlers
  const handleDismissInvestmentReminder = () => {
    setDismissedReminders(prev => ({ ...prev, investments: true }));
  };

  const handleDismissLoanReminder = () => {
    setDismissedReminders(prev => ({ ...prev, loans: true }));
  };

  const handleDismissCreditCardOverdueReminder = () => {
    setDismissedReminders(prev => ({ ...prev, creditCardOverdue: true }));
  };

  const handleDismissCreditCardDueSoonReminder = () => {
    setDismissedReminders(prev => ({ ...prev, creditCardDueSoon: true }));
  };

  const handleDismissBillingCycleEntryReminder = () => {
    setDismissedReminders(prev => ({ ...prev, billingCycleEntry: true }));
  };

  const handleDismissLoanPaymentOverdueReminder = () => {
    setDismissedReminders(prev => ({ ...prev, loanPaymentOverdue: true }));
  };

  const handleDismissLoanPaymentDueSoonReminder = () => {
    setDismissedReminders(prev => ({ ...prev, loanPaymentDueSoon: true }));
  };

  const handleDismissInsuranceClaimReminder = () => {
    setDismissedReminders(prev => ({ ...prev, insuranceClaims: true }));
  };

  const handleDismissAutoGeneratedCycleReminder = () => {
    setDismissedReminders(prev => ({ ...prev, autoGeneratedCycles: true }));
  };

  const handleInvestmentReminderClick = () => {
    setShowInvestmentsModal(true);
  };

  const handleLoanReminderClick = () => {
    setShowLoansModal(true);
  };

  const handleCreditCardReminderClick = () => {
    setShowPaymentMethodsModal(true);
  };

  const handleLoanPaymentReminderClick = (loanId) => {
    // Open loans modal - if a specific loanId is provided, it could be used to highlight that loan
    setShowLoansModal(true);
  };

  /**
   * Handle insurance claim reminder click
   * Filter expense list to show pending insurance claims
   * _Requirements: 3.1, 3.2_
   */
  const handleInsuranceClaimReminderClick = () => {
    // Dispatch custom event to filter expense list by insurance status
    window.dispatchEvent(new CustomEvent('filterByInsuranceStatus', {
      detail: { insuranceFilter: 'in_progress' }
    }));
  };

  /**
   * Handle auto-generated cycle banner click
   * Opens the Payment Methods modal so user can navigate to the credit card detail view
   * _Requirements: 2.3_
   */
  const handleAutoGeneratedCycleClick = () => {
    setShowPaymentMethodsModal(true);
  };

  /**
   * Handle budget alert reminder click
   * Navigate to expense list filtered by category
   * _Requirements: 6.4_
   */
  const handleBudgetAlertReminderClick = (category) => {
    // Dispatch custom event to navigate to expense list with category filter
    window.dispatchEvent(new CustomEvent('navigateToExpenseList', {
      detail: { categoryFilter: category }
    }));
  };

  const handleClosePaymentMethodsModal = async () => {
    setShowPaymentMethodsModal(false);
    await fetchReminderStatus();
  };

  /**
   * Handle auto-log payment confirmation
   * _Requirements: 4.4_
   */
  const handleAutoLogPayment = async (suggestion) => {
    setAutoLogLoading(true);
    try {
      const response = await fetch(
        API_ENDPOINTS.LOAN_PAYMENT_AUTO_LOG(suggestion.loanId),
        {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json'
          },
          body: JSON.stringify({
            fixed_expense_id: suggestion.fixedExpenseId,
            year: selectedYear,
            month: selectedMonth
          })
        }
      );

      if (!response.ok) {
        const errorData = await response.json();
        throw new Error(errorData.error || 'Failed to auto-log payment');
      }

      // Remove the logged suggestion from the list
      setAutoLogSuggestions(prev => 
        prev.filter(s => s.fixedExpenseId !== suggestion.fixedExpenseId)
      );

      // Refresh reminder status to update loan payment reminders
      await fetchReminderStatus();
      
      // Refresh summary data to update loan balances
      await fetchSummaryData();
    } catch (err) {
      console.error('Error auto-logging payment:', err);
      // Could show an error toast here
    } finally {
      setAutoLogLoading(false);
    }
  };

  /**
   * Handle skip auto-log suggestion
   * _Requirements: 4.5_
   */
  const handleSkipAutoLog = (suggestion) => {
    // Remove the skipped suggestion from the list
    setAutoLogSuggestions(prev => 
      prev.filter(s => s.fixedExpenseId !== suggestion.fixedExpenseId)
    );
  };

  /**
   * Handle dismiss all auto-log suggestions
   */
  const handleDismissAllAutoLog = () => {
    setDismissedAutoLog(true);
    setAutoLogSuggestions([]);
  };

  // Get IDs of investments/loans that need updates
  const investmentsNeedingUpdate = reminderStatus.investments
    ? reminderStatus.investments.filter(inv => !inv.hasValue).map(inv => inv.id)
    : [];
  
  const loansNeedingUpdate = reminderStatus.loans
    ? reminderStatus.loans.filter(loan => !loan.hasBalance).map(loan => loan.id)
    : [];

  // Format currency
  const formatCurrency = (amount) => {
    return new Intl.NumberFormat('en-CA', {
      style: 'currency',
      currency: 'CAD'
    }).format(amount);
  };

  // Get month name from month number
  const getMonthName = (monthNumber) => {
    const monthNames = [
      'January', 'February', 'March', 'April', 'May', 'June',
      'July', 'August', 'September', 'October', 'November', 'December'
    ];
    return monthNames[monthNumber - 1] || '';
  };

  // Calculate total notification count for NotificationsSection
  // _Requirements: 7.2, 7.5_
  // Note: Budget alerts count is managed by BudgetAlertManager and always counted as 1 if visible
  const calculateNotificationCount = () => {
    let count = 0;
    
    // Credit card overdue
    if (reminderStatus.creditCardReminders?.overdueCount > 0 && !dismissedReminders.creditCardOverdue) {
      count++;
    }
    // Credit card due soon
    if (reminderStatus.creditCardReminders?.dueSoonCount > 0 && !dismissedReminders.creditCardDueSoon) {
      count++;
    }
    // Billing cycle entry
    if (reminderStatus.billingCycleReminders?.needsEntryCount > 0 && !dismissedReminders.billingCycleEntry) {
      count++;
    }
    // Loan payment overdue
    if (reminderStatus.loanPaymentReminders?.overdueCount > 0 && !dismissedReminders.loanPaymentOverdue) {
      count++;
    }
    // Loan payment due soon
    if (reminderStatus.loanPaymentReminders?.dueSoonCount > 0 && !dismissedReminders.loanPaymentDueSoon) {
      count++;
    }
    // Insurance claims
    if (reminderStatus.insuranceClaimReminders?.hasPendingClaims && !dismissedReminders.insuranceClaims) {
      count++;
    }
    // Budget alerts - BudgetAlertManager handles its own visibility
    // We count it as 1 notification when visible (the component handles internal alert count)
    if (budgetAlertsVisible) {
      count++;
    }
    // Investment data reminders
    if (reminderStatus.hasActiveInvestments && reminderStatus.missingInvestments > 0 && !dismissedReminders.investments) {
      count++;
    }
    // Loan data reminders
    if (reminderStatus.hasActiveLoans && reminderStatus.missingLoans > 0 && !dismissedReminders.loans) {
      count++;
    }
    // Auto-generated billing cycle notifications
    if (reminderStatus.autoGeneratedCycleNotifications?.count > 0 && !dismissedReminders.autoGeneratedCycles) {
      count++;
    }
    
    return count;
  };

  const notificationCount = calculateNotificationCount();

  if (loading) {
    return (
      <div className="summary-panel">
        <h2>Monthly Summary</h2>
        <div className="loading-message">Loading summary...</div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="summary-panel">
        <h2>Monthly Summary</h2>
        <div className="error-message">Error: {error}</div>
      </div>
    );
  }

  if (!summary) {
    return null;
  }

  return (
    <div className="summary-panel">
      {/* Notifications Section - Contains all reminder banners */}
      {/* _Requirements: 7.1, 7.2, 7.3, 7.4, 7.5_ */}
      <NotificationsSection notificationCount={notificationCount}>
        {/* Credit Card Overdue Reminders - Most urgent, show first */}
        {reminderStatus.creditCardReminders?.overdueCount > 0 && 
         !dismissedReminders.creditCardOverdue && (
          <CreditCardReminderBanner
            cards={reminderStatus.creditCardReminders.overdueCards}
            isOverdue={true}
            onDismiss={handleDismissCreditCardOverdueReminder}
            onClick={handleCreditCardReminderClick}
          />
        )}

        {/* Credit Card Due Soon Reminders */}
        {reminderStatus.creditCardReminders?.dueSoonCount > 0 && 
         !dismissedReminders.creditCardDueSoon && (
          <CreditCardReminderBanner
            cards={reminderStatus.creditCardReminders.dueSoonCards}
            isOverdue={false}
            onDismiss={handleDismissCreditCardDueSoonReminder}
            onClick={handleCreditCardReminderClick}
          />
        )}

        {/* Billing Cycle Entry Reminders - Requirements: 4.1, 4.2, 4.4 */}
        {reminderStatus.billingCycleReminders?.needsEntryCount > 0 && 
         !dismissedReminders.billingCycleEntry && (
          <BillingCycleReminderBanner
            cards={reminderStatus.billingCycleReminders.cardsNeedingEntry}
            onDismiss={handleDismissBillingCycleEntryReminder}
            onClick={handleCreditCardReminderClick}
          />
        )}

        {/* Auto-Generated Billing Cycle Notifications - Requirements: 2.1, 2.3 */}
        {reminderStatus.autoGeneratedCycleNotifications?.count > 0 && 
         !dismissedReminders.autoGeneratedCycles && (
          <AutoGeneratedCycleBanner
            cycles={reminderStatus.autoGeneratedCycleNotifications.cycles}
            onDismiss={handleDismissAutoGeneratedCycleReminder}
            onClick={handleAutoGeneratedCycleClick}
          />
        )}

        {/* Loan Payment Overdue Reminders - Requirements: 5.1, 5.3, 5.4 */}
        {reminderStatus.loanPaymentReminders?.overdueCount > 0 && 
         !dismissedReminders.loanPaymentOverdue && (
          <LoanPaymentReminderBanner
            payments={reminderStatus.loanPaymentReminders.overduePayments}
            isOverdue={true}
            onDismiss={handleDismissLoanPaymentOverdueReminder}
            onClick={handleLoanPaymentReminderClick}
          />
        )}

        {/* Loan Payment Due Soon Reminders - Requirements: 5.1, 5.3, 5.5 */}
        {reminderStatus.loanPaymentReminders?.dueSoonCount > 0 && 
         !dismissedReminders.loanPaymentDueSoon && (
          <LoanPaymentReminderBanner
            payments={reminderStatus.loanPaymentReminders.dueSoonPayments}
            isOverdue={false}
            onDismiss={handleDismissLoanPaymentDueSoonReminder}
            onClick={handleLoanPaymentReminderClick}
          />
        )}

        {/* Insurance Claim Reminders - Requirements: 2.1, 2.2, 2.3, 2.4, 2.5 */}
        {reminderStatus.insuranceClaimReminders?.hasPendingClaims && 
         !dismissedReminders.insuranceClaims && (
          <InsuranceClaimReminderBanner
            claims={reminderStatus.insuranceClaimReminders.pendingClaims}
            onDismiss={handleDismissInsuranceClaimReminder}
            onClick={handleInsuranceClaimReminderClick}
          />
        )}

        {/* Budget Alert Reminders - Requirements: 6.1, 6.2, 6.4 */}
        {/* BudgetAlertManager handles its own data fetching, caching, and dismissal */}
        {/* It notifies parent of actual visibility via onVisibilityChange callback */}
        <BudgetAlertManager
          year={selectedYear}
          month={selectedMonth}
          refreshTrigger={refreshTrigger}
          onClick={handleBudgetAlertReminderClick}
          onVisibilityChange={setBudgetAlertsVisible}
        />

        {/* Investment Data Reminders */}
        {reminderStatus.hasActiveInvestments && 
         reminderStatus.missingInvestments > 0 && 
         !dismissedReminders.investments && (
          <DataReminderBanner
            type="investment"
            count={reminderStatus.missingInvestments}
            monthName={getMonthName(selectedMonth)}
            onDismiss={handleDismissInvestmentReminder}
            onClick={handleInvestmentReminderClick}
          />
        )}

        {/* Loan Data Reminders */}
        {reminderStatus.hasActiveLoans && 
         reminderStatus.missingLoans > 0 && 
         !dismissedReminders.loans && (
          <DataReminderBanner
            type="loan"
            count={reminderStatus.missingLoans}
            monthName={getMonthName(selectedMonth)}
            onDismiss={handleDismissLoanReminder}
            onClick={handleLoanReminderClick}
          />
        )}
      </NotificationsSection>

      {/* Monthly Summary Header - Now below NotificationsSection */}
      {/* _Requirements: 7.1_ */}
      <h2>Monthly Summary</h2>

      {/* Summary Cards Grid - Order: Income, Fixed, Variable, Balance */}
      <div className="summary-grid">
        {/* Monthly Income Card */}
        <div className="summary-card income-card">
          <div className="card-header">
            <span className="card-icon">🏠</span>
            <span className="card-title">Monthly Income</span>
          </div>
          <div className="card-value positive">{formatCurrency(summary.monthlyGross || 0)}</div>
          <button className="card-action-btn" onClick={handleOpenIncomeModal}>
            Manage Income
          </button>
        </div>

        {/* Fixed Expenses Card */}
        <div className="summary-card">
          <div className="card-header">
            <span className="card-icon">📝</span>
            <span className="card-title">Fixed Expenses</span>
          </div>
          <div className="card-value expense-value">{formatCurrency(summary.totalFixedExpenses || 0)}</div>
          <button className="card-action-btn" onClick={handleOpenFixedExpensesModal}>
            Manage Fixed
          </button>
        </div>

        {/* Variable Expenses Card */}
        <div className="summary-card highlight-card">
          <div className="card-header">
            <span className="card-icon">💰</span>
            <span className="card-title">Variable Expenses</span>
          </div>
          <div className="card-value expense-value">{formatCurrency(summary.total || 0)}</div>
        </div>

        {/* Balance Card */}
        <div className="summary-card balance-card">
          <div className="card-header">
            <span className="card-icon">📊</span>
            <span className="card-title">Balance</span>
          </div>
          <div className={`card-value ${(summary.monthlyGross - summary.total - summary.totalFixedExpenses) >= 0 ? 'positive' : 'negative'}`}>
            {formatCurrency((summary.monthlyGross || 0) - (summary.total || 0) - (summary.totalFixedExpenses || 0))}
          </div>
          <div className="card-subtitle">Income - All Expenses</div>
        </div>

        {/* Collapsible: Weekly Breakdown */}
        <div className="summary-card full-width">
          <div className="collapsible-header" onClick={() => setWeeklyOpen(!weeklyOpen)}>
            <div className="card-header">
              <span className="card-icon">📅</span>
              <span className="card-title">Weekly Breakdown</span>
            </div>
            <span className="collapse-icon">{weeklyOpen ? '▼' : '▶'}</span>
          </div>
          {weeklyOpen && (
            <div className="card-content">
              <div className="compact-list">
                {Object.entries(summary.weeklyTotals || {}).map(([week, amount]) => {
                  const previousAmount = previousSummary?.weeklyTotals?.[week];
                  return (
                    <div key={week} className="compact-item">
                      <span>Week {week.replace('week', '')}</span>
                      <span>
                        {formatCurrency(amount)}
                        <TrendIndicator currentValue={amount} previousValue={previousAmount} />
                      </span>
                    </div>
                  );
                })}
              </div>
            </div>
          )}
        </div>

        {/* Collapsible: Payment Methods */}
        <div className="summary-card full-width">
          <div className="collapsible-header" onClick={() => setPaymentOpen(!paymentOpen)}>
            <div className="card-header">
              <span className="card-icon">💳</span>
              <span className="card-title">Payment Methods</span>
            </div>
            <span className="collapse-icon">{paymentOpen ? '▼' : '▶'}</span>
          </div>
          {paymentOpen && (
            <div className="card-content">
              <div className="compact-list">
                {Object.entries(summary.methodTotals || {}).map(([method, amount]) => {
                  const previousAmount = previousSummary?.methodTotals?.[method];
                  return (
                    <div key={method} className="compact-item">
                      <span>{method}</span>
                      <span>
                        {formatCurrency(amount)}
                        <TrendIndicator currentValue={amount} previousValue={previousAmount} />
                      </span>
                    </div>
                  );
                })}
              </div>
            </div>
          )}
        </div>

        {/* Collapsible: Expense Types */}
        <div className="summary-card full-width">
          <div className="collapsible-header" onClick={() => setExpenseTypesOpen(!expenseTypesOpen)}>
            <div className="card-header">
              <span className="card-icon">🏷️</span>
              <span className="card-title">Expense Types</span>
            </div>
            <span className="collapse-icon">{expenseTypesOpen ? '▼' : '▶'}</span>
          </div>
          {expenseTypesOpen && (
            <div className="card-content">
              <div className="compact-list">
                {Object.entries(summary.typeTotals || {})
                  .sort(([, a], [, b]) => b - a)
                  .map(([type, amount]) => {
                    const previousAmount = previousSummary?.typeTotals?.[type];
                    return (
                      <div key={type} className="compact-item">
                        <span>{type}</span>
                        <span>
                          {formatCurrency(amount)}
                          <TrendIndicator currentValue={amount} previousValue={previousAmount} />
                        </span>
                      </div>
                    );
                  })}
              </div>
            </div>
          )}
        </div>

        {/* Loans Card */}
        <div className="summary-card loans-card">
          <div className="card-header">
            <span className="card-icon">🏦</span>
            <span className="card-title">Outstanding Debt</span>
          </div>
          {loans.length > 0 ? (
            <>
              <div className="card-value negative">{formatCurrency(totalOutstandingDebt)}</div>
              <button className="card-action-btn" onClick={handleOpenLoansModal}>
                Manage Loans
              </button>
            </>
          ) : (
            <>
              <div className="card-value">{formatCurrency(0)}</div>
              <button className="card-action-btn" onClick={handleOpenLoansModal}>
                Manage Loans
              </button>
            </>
          )}
        </div>

        {/* Investments Card */}
        <div className="summary-card investments-card">
          <div className="card-header">
            <span className="card-icon">📈</span>
            <span className="card-title">Total Investments</span>
          </div>
          {investments.length > 0 ? (
            <>
              <div className="card-value positive">{formatCurrency(totalInvestmentValue)}</div>
              <button className="card-action-btn" onClick={handleOpenInvestmentsModal}>
                Manage Investments
              </button>
            </>
          ) : (
            <>
              <div className="card-value">{formatCurrency(0)}</div>
              <button className="card-action-btn" onClick={handleOpenInvestmentsModal}>
                Manage Investments
              </button>
            </>
          )}
        </div>

        {/* Net Worth Card */}
        <div className="summary-card net-worth-card">
          <div className="card-header">
            <span className="card-icon">💎</span>
            <span className="card-title">Net Worth</span>
          </div>
          <div className={`card-value ${(totalInvestmentValue - totalOutstandingDebt) >= 0 ? 'positive' : 'negative'}`}>
            {formatCurrency(totalInvestmentValue - totalOutstandingDebt)}
          </div>
          <div className="net-worth-breakdown">
            <span className="assets-label">Assets: {formatCurrency(totalInvestmentValue)}</span>
            <span className="separator">-</span>
            <span className="liabilities-label">Liabilities: {formatCurrency(totalOutstandingDebt)}</span>
          </div>
          <div className="card-subtitle">Current month position</div>
        </div>
      </div>

      {showIncomeModal && (
        <IncomeManagementModal
          isOpen={showIncomeModal}
          onClose={handleCloseIncomeModal}
          year={selectedYear}
          month={selectedMonth}
          onUpdate={handleCloseIncomeModal}
        />
      )}

      {showFixedExpensesModal && (
        <FixedExpensesModal
          isOpen={showFixedExpensesModal}
          onClose={handleCloseFixedExpensesModal}
          year={selectedYear}
          month={selectedMonth}
          onUpdate={handleCloseFixedExpensesModal}
        />
      )}

      {showLoansModal && (
        <LoansModal
          isOpen={showLoansModal}
          onClose={handleCloseLoansModal}
          year={selectedYear}
          month={selectedMonth}
          onUpdate={handleCloseLoansModal}
          highlightIds={loansNeedingUpdate}
        />
      )}

      {showInvestmentsModal && (
        <InvestmentsModal
          isOpen={showInvestmentsModal}
          onClose={handleCloseInvestmentsModal}
          year={selectedYear}
          month={selectedMonth}
          onUpdate={handleInvestmentsUpdate}
          highlightIds={investmentsNeedingUpdate}
        />
      )}

      {showPaymentMethodsModal && (
        <PaymentMethodsModal
          isOpen={showPaymentMethodsModal}
          onClose={handleClosePaymentMethodsModal}
        />
      )}

      {/* Auto-Log Prompt - Requirements: 4.4, 4.5 */}
      {autoLogSuggestions.length > 0 && !dismissedAutoLog && (
        <AutoLogPrompt
          suggestions={autoLogSuggestions}
          onLogPayment={handleAutoLogPayment}
          onSkip={handleSkipAutoLog}
          onDismissAll={handleDismissAllAutoLog}
          loading={autoLogLoading}
        />
      )}
    </div>
  );
};

export default SummaryPanel;
